import java.awt.*;
import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class Menu {
    private JFrame frame;
    private JLabel label;
    private int counter = 0;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private JButton button5;
    private JButton button6;

    /**
     * Launch the application.
     */
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Menu window = new Menu();
                    window.frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    /**
     * Create the application.
     */
    public Menu() {
        initialize();
    }

    /**
     * Initialize the contents of the frame.
     */
    private void initialize() {
        frame = new JFrame();
        frame.setBounds(200, 200, 500, 300);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().setLayout(null);

        JButton button1 = new JButton("\u0417\u0430\u0434\u0430\u043D\u0438\u0435 1");
        button1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ZD1.main(new String[0]);
            }
        });
        button1.setBounds(50, 50, 100, 23);
        frame.getContentPane().add(button1);

        JButton button2 = new JButton("\u0417\u0430\u0434\u0430\u043D\u0438\u0435 2");
        button2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ZD2.main(new String[0]);
            }
        });
        button2.setBounds(50, 100, 100, 23);
        frame.getContentPane().add(button2);

        JButton button3 = new JButton("\u0417\u0430\u0434\u0430\u043D\u0438\u0435 3");
        button3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                RunnerText.main(new String[0]);
            }
        });
        button3.setBounds(50, 150, 100, 23);
        frame.getContentPane().add(button3);

        JButton button4 = new JButton("\u0417\u0430\u0434\u0430\u043D\u0438\u0435 4");
        button4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ZD4.main(new String[0]);
            }
        });
        button4.setBounds(200, 50, 100, 23);
        frame.getContentPane().add(button4);

        JButton button5 = new JButton("\u0417\u0430\u0434\u0430\u043D\u0438\u0435 5");
        button5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ZD5.main(new String[0]);
            }
        });
        button5.setBounds(200, 100, 100, 23);
        frame.getContentPane().add(button5);

        JButton button6 = new JButton("\u0417\u0430\u0434\u0430\u043D\u0438\u0435 6");
        button6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ZD6.main(new String[0]);
            }
        });
        button6.setBounds(200, 150, 100, 23);
        frame.getContentPane().add(button6);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }
}